<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="purpletalk-Latitude-E5450" name="amazon" tests="1" failures="1" timestamp="28 May 2020 06:28:04 GMT" time="23.076" errors="0">
  <testcase name="searchProduct" time="7.827" classname="com.automation.test.AmazonSiteTest">
    <failure type="java.lang.AssertionError" message="expected [450] but found [262]">
      <![CDATA[java.lang.AssertionError: expected [450] but found [262]
	at com.automation.test.AmazonSiteTest.searchProduct(AmazonSiteTest.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- searchProduct -->
</testsuite> <!-- amazon -->
